# Generated by Django 5.1.4 on 2025-02-02 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(default="images/default.png")),
                ("folder_url", models.URLField(default="我的收藏/")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.CharField(max_length=255)),
                ("image_size", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "图片",
                "verbose_name_plural": "图片",
                "db_table": "image",
            },
        ),
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("tag_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "图片标签关系",
                "verbose_name_plural": "图片标签关系",
                "db_table": "image_tag",
                "unique_together": {("image_id", "tag_name")},
            },
        ),
    ]
