# Generated by Django 5.1.4 on 2025-01-25 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagetag",
            name="image_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
