# Generated by Django 5.1.4 on 2025-01-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片标签关系",
                "verbose_name_plural": "图片标签关系",
                "db_table": "image_tag",
                "unique_together": {("image", "tag_name")},
            },
        ),
    ]
