# Generated by Django 5.1.4 on 2025-01-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_imagetag_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_size",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
