# Generated by Django 5.1.4 on 2025-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_image_image_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="folder_url",
            field=models.URLField(default="我的收藏/"),
        ),
    ]
