# Generated by Django 5.1.4 on 2025-02-02 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("space", models.IntegerField(default=0, verbose_name="消耗空间")),
                (
                    "username",
                    models.CharField(max_length=150, unique=True, verbose_name="用户名"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=255, verbose_name="密码"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatar/default.png",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="注册时间"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="最后登录时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否在线")),
                (
                    "membership",
                    models.CharField(
                        choices=[
                            ("free", "免费会员"),
                            ("silver", "银牌会员"),
                            ("gold", "金牌会员"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="会员权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
                "db_table": "verification_code",
            },
        ),
    ]
