# Generated by Django 5.1.4 on 2025-02-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="space",
            new_name="used_space",
        ),
    ]
