# Generated by Django 5.1.4 on 2025-01-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="left_space",
            field=models.IntegerField(default=0, verbose_name="剩余空间"),
        ),
        migrations.AddField(
            model_name="user",
            name="vertification_code",
            field=models.CharField(blank=True, max_length=6, verbose_name="验证码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatar/avatar.png",
                null=True,
                upload_to="avatars/",
                verbose_name="头像",
            ),
        ),
    ]
