# Generated by Django 5.1.4 on 2025-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_space_user_used_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="used_space",
            field=models.FloatField(default=0.0, verbose_name="消耗空间"),
        ),
    ]
