# Generated by Django 5.1.4 on 2025-01-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_left_space_user_vertification_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="vertification_code",
            new_name="verification_code",
        ),
    ]
