# Generated by Django 5.1.4 on 2025-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_is_staff_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="used_space",
            field=models.FloatField(default=1024.0, verbose_name="已用空间"),
        ),
    ]
