# Generated by Django 5.1.6 on 2025-02-11 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRcodeId",
            fields=[
                (
                    "qrcode_id",
                    models.UUIDField(
                        help_text="二维码id", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "qrcode_id",
            },
        ),
        migrations.CreateModel(
            name="TemporaryToken",
            fields=[
                (
                    "temporary_token",
                    models.UUIDField(
                        help_text="临时token", primary_key=True, serialize=False
                    ),
                ),
                (
                    "qrcode",
                    models.ForeignKey(
                        help_text="二维码id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qr_code.qrcodeid",
                    ),
                ),
            ],
            options={
                "db_table": "temporary_token",
            },
        ),
    ]
