# Generated by Django 5.1.6 on 2025-02-11 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_code", "0002_qrcodeid_state_temporarytoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodeid",
            name="qrcode_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
