# Generated by Django 5.1.4 on 2025-02-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="consumptionHistory",
            fields=[
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, help_text="修改时间"),
                ),
                (
                    "trade_no",
                    models.UUIDField(
                        editable=False,
                        help_text="订单号",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trade_time",
                    models.DateTimeField(auto_now=True, help_text="交易时间"),
                ),
                ("trade_spent", models.IntegerField(help_text="消费金额")),
                (
                    "is_success",
                    models.BooleanField(default=False, help_text="是否成功"),
                ),
                (
                    "trade_description",
                    models.CharField(help_text="套餐类型", max_length=4, null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="用户id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time"],
                "abstract": False,
            },
        ),
    ]
