# Generated by Django 5.1.6 on 2025-02-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumptionHistory",
            fields=[
                (
                    "trade_no",
                    models.UUIDField(
                        help_text="订单号", primary_key=True, serialize=False
                    ),
                ),
                (
                    "trade_time",
                    models.DateTimeField(auto_now=True, help_text="交易时间"),
                ),
                ("trade_spent", models.FloatField(help_text="消费金额")),
                (
                    "is_success",
                    models.BooleanField(default=False, help_text="是否成功"),
                ),
                (
                    "trade_description",
                    models.CharField(help_text="套餐类型", max_length=4, null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="用户id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "consumption_history",
            },
        ),
        migrations.CreateModel(
            name="ContinueTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(help_text="会员类型", max_length=4)),
                ("deadline", models.DateTimeField(help_text="会员截止时间")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "continue_time",
            },
        ),
    ]
