# Generated by Django 5.1.4 on 2025-02-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumptionhistory",
            options={},
        ),
        migrations.AlterModelTable(
            name="consumptionhistory",
            table="consumptionHistory",
        ),
    ]
