# Generated by Django 5.1.4 on 2025-02-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0002_alter_consumptionhistory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumptionhistory",
            name="created_time",
        ),
        migrations.RemoveField(
            model_name="consumptionhistory",
            name="last_modified",
        ),
    ]
