# Generated by Django 5.1.4 on 2025-02-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0004_alter_consumptionhistory_trade_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumptionhistory",
            name="trade_no",
            field=models.CharField(
                help_text="订单号", max_length=36, primary_key=True, serialize=False
            ),
        ),
    ]
